Saving last configuration file to .certora_internal/25_04_06_10_48_50_194/run.conf
There is no TAC file. Going to script CertoraProver/certoraBuild.py to main_with_args()
Creating dir /home/pedro/Desktop/UFPE - Março/erc3525-certora/projeto_certora/certora/conf/.certora_internal/25_04_06_10_48_50_194/.certora_config
In /home/pedro/Desktop/UFPE - Março/erc3525-certora/projeto_certora/certora/specs/ERC3525.spec, found the imports: []
copying spec file /home/pedro/Desktop/UFPE - Março/erc3525-certora/projeto_certora/certora/specs/ERC3525.spec to /home/pedro/Desktop/UFPE - Março/erc3525-certora/projeto_certora/certora/conf/.certora_internal/25_04_06_10_48_50_194/.certora_sources/.0_ERC3525.spec.spec
writing /home/pedro/Desktop/UFPE - Março/erc3525-certora/projeto_certora/certora/conf/.certora_internal/25_04_06_10_48_50_194/.certora_verify.json
Failed to run Certora Prover locally. Please check the errors below for problems in the specifications (.spec files) or the prover_args defined in the .conf file.
[main] ERROR ALWAYS - Found errors in ../specs/ERC3525.spec:
[main] ERROR ALWAYS - Error in spec file (ERC3525.spec:1:23): Since CVL 2, `using` statements must end with `;`
build failed
